# Generated by Django 4.1.6 on 2023-02-12 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tax',
            options={'verbose_name': 'Налог', 'verbose_name_plural': 'Налоги'},
        ),
        migrations.AddField(
            model_name='order',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stripe_api.tax', verbose_name='Процент налога'),
        ),
        migrations.AddField(
            model_name='tax',
            name='tax_size',
            field=models.PositiveIntegerField(default=10, verbose_name='Налог'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.PROTECT, to='stripe_api.discount', verbose_name='Размер скидки'),
        ),
    ]
