# Generated by Django 4.1.6 on 2023-02-12 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_api', '0003_alter_tax_options_item_currency_alter_order_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(choices=[('rub', 'Рубль'), ('usd', 'Доллар')], default='rub', max_length=3, verbose_name='Валюта'),
        ),
    ]
