# Generated by Django 4.1.6 on 2023-02-12 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_api', '0004_order_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tax',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='stripe_api.tax', verbose_name='Процент налога'),
        ),
    ]
