# Generated by Django 4.1.6 on 2023-02-13 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_api', '0005_item_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discount',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.PROTECT, to='stripe_api.discount', verbose_name='Размер скидки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='stripe_api.tax', verbose_name='Процент налога'),
        ),
    ]
